version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - curl -s https://releases.hashicorp.com/terraform/1.6.6/terraform_1.6.6_linux_amd64.zip -o terraform.zip
      - unzip terraform.zip
      - mv terraform /usr/local/bin/
      - terraform version

  pre_build:
    commands:
      - cd terraform
      - terraform init

  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve
